version: '3'
services:
  email:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORTA_DA_APLICACAO}
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - ${PORTA_BANCO_DOCKER}